import type { TeachingStyle } from '../entities/common.js';
import type { Hint, HintType } from '../entities/session.js';
import type { HintId, SessionId } from '../entities/common.js';

/**
 * The complete context assembled by the Prompt Builder before calling the Teaching Engine.
 */
export interface PromptPayload {
  readonly systemInstructions: string;
  readonly userMessage: string;
  readonly conversationHistory: ConversationTurn[];
  readonly maxTokens: number;
  readonly temperature: number;
}

export interface ConversationTurn {
  readonly role: 'user' | 'assistant';
  readonly content: string;
}

/**
 * A structured hint response from the Teaching Engine.
 */
export interface HintResponse {
  readonly content: string;
  readonly hintType: HintType;
  readonly confidence: number;  // 0.0–1.0: how confident the engine is this hint is appropriate
  readonly followUpQuestion?: string;
}

/**
 * A post-session reflection generated by the Teaching Engine.
 */
export interface ReflectionResponse {
  readonly summary: string;
  readonly conceptsLearned: string[];
  readonly mistakesFixed: string[];
  readonly optimizationAchieved: string | null;
  readonly topicsStrengthened: string[];
  readonly areasToImprove: string[];
  readonly encouragement: string;
}

/**
 * A streaming chunk from the Teaching Engine.
 */
export interface TeachingChunk {
  readonly delta: string;
  readonly isDone: boolean;
}

/**
 * Domain-level abstraction for the AI teaching capability.
 *
 * This is the boundary between the domain and all AI providers.
 * Internally implemented by an IReasoningProvider, but the domain
 * only sees the teaching interface — not the raw LLM.
 *
 * One ITeachingEngine per session; teaching style can be adapted mid-session.
 */
export interface ITeachingEngine {
  /**
   * Generate a Socratic hint. Never returns a full implementation.
   */
  generateHint(payload: PromptPayload): Promise<HintResponse>;

  /**
   * Stream a Socratic hint token-by-token for real-time display.
   */
  streamHint(payload: PromptPayload): AsyncIterable<TeachingChunk>;

  /**
   * Generate a post-session reflection.
   */
  generateReflection(payload: PromptPayload): Promise<ReflectionResponse>;

  /**
   * Adapt the teaching style for the current session.
   * Affects all subsequent generateHint / streamHint calls.
   */
  adaptStyle(style: TeachingStyle): void;

  /**
   * Returns the currently active teaching style.
   */
  getCurrentStyle(): TeachingStyle;
}

/**
 * Internal interface for raw LLM providers.
 * Used only inside adapter implementations — never in domain code.
 */
export interface IReasoningProvider {
  complete(payload: PromptPayload): Promise<string>;
  stream(payload: PromptPayload): AsyncIterable<string>;
  readonly modelId: string;
  readonly providerName: string;
}
